### ISSUE TITLE
GitHub repository not notable enough? 

### ISSUE THREAD

**Issue by dardo82** [Homebrew/homebrew-head-only#175] opened 2015-10-17 11:46 UTC
I've opened a pull request [here] (https://github.com/Homebrew/homebrew-head-only/pull/172), but it says that [the GitHub repository is not notable enough] (http://bot.brew.sh/job/Homebrew%20Head-Only%20Pull%20Requests/302/version=mavericks/testReport/junit/brew-test-bot/mavericks/audit_homebrew_head_only_uhubctl___strict___online/). 
Then how comes that [this] (https://github.com/Orc/Zzz) and [this] (https://github.com/kylef/wol) are instead in the tap while not being notable the same and even duplicating commands already available in the system?

**Comment by bfontaine** [comment] 2015-10-17 12:32
I’m closing this issue as a duplicate of https://github.com/Homebrew/homebrew/issues/45065

**Closed by bfontaine** 2015-10-17 12:32 UTC

**Comment by dardo82** [comment] 2015-10-17 13:02
How do i delete this? 
Can i delete an issue?
Or i can only edit one?

**Comment by bfontaine** [comment] 2015-10-17 13:05
We can’t delete issues on GitHub.

**Comment by dardo82** [comment] 2015-10-17 13:06
Then i think this is an issue! ;-)
